// Generated by generate_catalog.py from the reviewed S1-02 catalog.
use serde::{Deserialize, Serialize};
use toolkit_canonical_errors::ProblemCategory;
use toolkit_gts::gts_id;
/// Closed `OrderState` registry from the Orders design.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum OrderState {
    /// `draft`.
    #[serde(rename = "draft")]
    Draft,
    /// `submitted`.
    #[serde(rename = "submitted")]
    Submitted,
    /// `pending_approval`.
    #[serde(rename = "pending_approval")]
    PendingApproval,
    /// `approved`.
    #[serde(rename = "approved")]
    Approved,
    /// `in_fulfillment`.
    #[serde(rename = "in_fulfillment")]
    InFulfillment,
    /// `on_hold`.
    #[serde(rename = "on_hold")]
    OnHold,
    /// `completed`.
    #[serde(rename = "completed")]
    Completed,
    /// `rejected`.
    #[serde(rename = "rejected")]
    Rejected,
    /// `cancelled`.
    #[serde(rename = "cancelled")]
    Cancelled,
    /// `fulfillment_failed`.
    #[serde(rename = "fulfillment_failed")]
    FulfillmentFailed,
    /// `expired`.
    #[serde(rename = "expired")]
    Expired,
}
impl OrderState {
    /// All registered values.
    pub const ALL: &'static [Self] = &[
        Self::Draft,
        Self::Submitted,
        Self::PendingApproval,
        Self::Approved,
        Self::InFulfillment,
        Self::OnHold,
        Self::Completed,
        Self::Rejected,
        Self::Cancelled,
        Self::FulfillmentFailed,
        Self::Expired,
    ];
}
/// Closed `Trigger` registry from the Orders design.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Trigger {
    /// `create`.
    #[serde(rename = "create")]
    Create,
    /// `draft-mutate`.
    #[serde(rename = "draft-mutate")]
    DraftMutate,
    /// `administrative-edit`.
    #[serde(rename = "administrative-edit")]
    AdministrativeEdit,
    /// `submit`.
    #[serde(rename = "submit")]
    Submit,
    /// `cancel`.
    #[serde(rename = "cancel")]
    Cancel,
    /// `auto-void`.
    #[serde(rename = "auto-void")]
    AutoVoid,
    /// `reflect-approval-required`.
    #[serde(rename = "reflect-approval-required")]
    ReflectApprovalRequired,
    /// `reflect-approval-not-required`.
    #[serde(rename = "reflect-approval-not-required")]
    ReflectApprovalNotRequired,
    /// `reflect-approval-granted`.
    #[serde(rename = "reflect-approval-granted")]
    ReflectApprovalGranted,
    /// `reflect-approval-denied`.
    #[serde(rename = "reflect-approval-denied")]
    ReflectApprovalDenied,
    /// `begin-fulfillment`.
    #[serde(rename = "begin-fulfillment")]
    BeginFulfillment,
    /// `report-spawn-signal`.
    #[serde(rename = "report-spawn-signal")]
    ReportSpawnSignal,
    /// `acknowledge-completed`.
    #[serde(rename = "acknowledge-completed")]
    AcknowledgeCompleted,
    /// `acknowledge-failed`.
    #[serde(rename = "acknowledge-failed")]
    AcknowledgeFailed,
    /// `cancel-workflow-mediated`.
    #[serde(rename = "cancel-workflow-mediated")]
    CancelWorkflowMediated,
    /// `amendment`.
    #[serde(rename = "amendment")]
    Amendment,
    /// `hold`.
    #[serde(rename = "hold")]
    Hold,
    /// `resume`.
    #[serde(rename = "resume")]
    Resume,
    /// `expire`.
    #[serde(rename = "expire")]
    Expire,
    /// `record-acceptance`.
    #[serde(rename = "record-acceptance")]
    RecordAcceptance,
    /// `force-fail-unreconciled`.
    #[serde(rename = "force-fail-unreconciled")]
    ForceFailUnreconciled,
}
impl Trigger {
    /// All registered values.
    pub const ALL: &'static [Self] = &[
        Self::Create,
        Self::DraftMutate,
        Self::AdministrativeEdit,
        Self::Submit,
        Self::Cancel,
        Self::AutoVoid,
        Self::ReflectApprovalRequired,
        Self::ReflectApprovalNotRequired,
        Self::ReflectApprovalGranted,
        Self::ReflectApprovalDenied,
        Self::BeginFulfillment,
        Self::ReportSpawnSignal,
        Self::AcknowledgeCompleted,
        Self::AcknowledgeFailed,
        Self::CancelWorkflowMediated,
        Self::Amendment,
        Self::Hold,
        Self::Resume,
        Self::Expire,
        Self::RecordAcceptance,
        Self::ForceFailUnreconciled,
    ];
}
#[expect(
    clippy::enum_variant_names,
    reason = "Published event identifiers retain the Orders prefix"
)]
/// Closed `EventKind` registry from the Orders design.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum EventKind {
    /// `OrderSubmitted`.
    #[serde(rename = "OrderSubmitted")]
    OrderSubmitted,
    /// `OrderApproved`.
    #[serde(rename = "OrderApproved")]
    OrderApproved,
    /// `OrderRejected`.
    #[serde(rename = "OrderRejected")]
    OrderRejected,
    /// `OrderAmended`.
    #[serde(rename = "OrderAmended")]
    OrderAmended,
    /// `OrderHeld`.
    #[serde(rename = "OrderHeld")]
    OrderHeld,
    /// `OrderResumed`.
    #[serde(rename = "OrderResumed")]
    OrderResumed,
    /// `OrderCancelled`.
    #[serde(rename = "OrderCancelled")]
    OrderCancelled,
    /// `OrderExpired`.
    #[serde(rename = "OrderExpired")]
    OrderExpired,
    /// `OrderCompleted`.
    #[serde(rename = "OrderCompleted")]
    OrderCompleted,
    /// `OrderFulfillmentFailed`.
    #[serde(rename = "OrderFulfillmentFailed")]
    OrderFulfillmentFailed,
    /// `OrderAcceptanceRecorded`.
    #[serde(rename = "OrderAcceptanceRecorded")]
    OrderAcceptanceRecorded,
}
impl EventKind {
    /// All registered values.
    pub const ALL: &'static [Self] = &[
        Self::OrderSubmitted,
        Self::OrderApproved,
        Self::OrderRejected,
        Self::OrderAmended,
        Self::OrderHeld,
        Self::OrderResumed,
        Self::OrderCancelled,
        Self::OrderExpired,
        Self::OrderCompleted,
        Self::OrderFulfillmentFailed,
        Self::OrderAcceptanceRecorded,
    ];
}
/// Closed `Reason` registry from the Orders design.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Reason {
    /// `not-admissible`.
    #[serde(rename = "not-admissible")]
    NotAdmissible,
    /// `version-conflict`.
    #[serde(rename = "version-conflict")]
    VersionConflict,
    /// `idempotency-mismatch`.
    #[serde(rename = "idempotency-mismatch")]
    IdempotencyMismatch,
    /// `still-processing`.
    #[serde(rename = "still-processing")]
    StillProcessing,
    /// `authorization-context-changed`.
    #[serde(rename = "authorization-context-changed")]
    AuthorizationContextChanged,
    /// `expected-version-required`.
    #[serde(rename = "expected-version-required")]
    ExpectedVersionRequired,
    /// `request-invalid`.
    #[serde(rename = "request-invalid")]
    RequestInvalid,
    /// `category-not-admitted`.
    #[serde(rename = "category-not-admitted")]
    CategoryNotAdmitted,
    /// `line-not-found`.
    #[serde(rename = "line-not-found")]
    LineNotFound,
    /// `commercial-field-immutable`.
    #[serde(rename = "commercial-field-immutable")]
    CommercialFieldImmutable,
    /// `mixed-field-classes`.
    #[serde(rename = "mixed-field-classes")]
    MixedFieldClasses,
    /// `line-cap-exceeded`.
    #[serde(rename = "line-cap-exceeded")]
    LineCapExceeded,
    /// `date-cascade-invalid`.
    #[serde(rename = "date-cascade-invalid")]
    DateCascadeInvalid,
    /// `axis-invalid`.
    #[serde(rename = "axis-invalid")]
    AxisInvalid,
    /// `contract-not-active`.
    #[serde(rename = "contract-not-active")]
    ContractNotActive,
    /// `contract-party-ineligible`.
    #[serde(rename = "contract-party-ineligible")]
    ContractPartyIneligible,
    /// `quantity-below-floor`.
    #[serde(rename = "quantity-below-floor")]
    QuantityBelowFloor,
    /// `market-inconsistent`.
    #[serde(rename = "market-inconsistent")]
    MarketInconsistent,
    /// `reference-unresolvable`.
    #[serde(rename = "reference-unresolvable")]
    ReferenceUnresolvable,
    /// `reference-duplicated`.
    #[serde(rename = "reference-duplicated")]
    ReferenceDuplicated,
    /// `currency-mixed`.
    #[serde(rename = "currency-mixed")]
    CurrencyMixed,
    /// `overlap-cardinality-exceeded`.
    #[serde(rename = "overlap-cardinality-exceeded")]
    OverlapCardinalityExceeded,
    /// `order-in-flight-for-key`.
    #[serde(rename = "order-in-flight-for-key")]
    OrderInFlightForKey,
    /// `overlap-key-unresolvable`.
    #[serde(rename = "overlap-key-unresolvable")]
    OverlapKeyUnresolvable,
    /// `pin-unresolvable`.
    #[serde(rename = "pin-unresolvable")]
    PinUnresolvable,
    /// `no-lines`.
    #[serde(rename = "no-lines")]
    NoLines,
    /// `catalog-predicates-unavailable`.
    #[serde(rename = "catalog-predicates-unavailable")]
    CatalogPredicatesUnavailable,
    /// `pricing-revision-unavailable`.
    #[serde(rename = "pricing-revision-unavailable")]
    PricingRevisionUnavailable,
    /// `pricing-revision-absent`.
    #[serde(rename = "pricing-revision-absent")]
    PricingRevisionAbsent,
    /// `catalog-pin-composition-unavailable`.
    #[serde(rename = "catalog-pin-composition-unavailable")]
    CatalogPinCompositionUnavailable,
    /// `order-binding-expired`.
    #[serde(rename = "order-binding-expired")]
    OrderBindingExpired,
    /// `order-binding-policy-missing`.
    #[serde(rename = "order-binding-policy-missing")]
    OrderBindingPolicyMissing,
    /// `purchase-capacity-exceeded`.
    #[serde(rename = "purchase-capacity-exceeded")]
    PurchaseCapacityExceeded,
    /// `overlap-key-unavailable`.
    #[serde(rename = "overlap-key-unavailable")]
    OverlapKeyUnavailable,
    /// `catalog-predicate-failed`.
    #[serde(rename = "catalog-predicate-failed")]
    CatalogPredicateFailed,
    /// `catalog-predicate-unevaluable`.
    #[serde(rename = "catalog-predicate-unevaluable")]
    CatalogPredicateUnevaluable,
    /// `identity-party-unavailable`.
    #[serde(rename = "identity-party-unavailable")]
    IdentityPartyUnavailable,
    /// `contract-resolution-unavailable`.
    #[serde(rename = "contract-resolution-unavailable")]
    ContractResolutionUnavailable,
    /// `overlap-presence-unevaluable`.
    #[serde(rename = "overlap-presence-unevaluable")]
    OverlapPresenceUnevaluable,
    /// `evaluation-unavailable`.
    #[serde(rename = "evaluation-unavailable")]
    EvaluationUnavailable,
    /// `indicative-tax-unavailable`.
    #[serde(rename = "indicative-tax-unavailable")]
    IndicativeTaxUnavailable,
    /// `market-divergence`.
    #[serde(rename = "market-divergence")]
    MarketDivergence,
    /// `overlap-collision`.
    #[serde(rename = "overlap-collision")]
    OverlapCollision,
    /// `payer-rebinding-requires-seller`.
    #[serde(rename = "payer-rebinding-requires-seller")]
    PayerRebindingRequiresSeller,
    /// `tenant-axis-immutable`.
    #[serde(rename = "tenant-axis-immutable")]
    TenantAxisImmutable,
    /// `administrative-field-in-amendment`.
    #[serde(rename = "administrative-field-in-amendment")]
    AdministrativeFieldInAmendment,
    /// `amendment-empty`.
    #[serde(rename = "amendment-empty")]
    AmendmentEmpty,
    /// `amendment-reason-invalid`.
    #[serde(rename = "amendment-reason-invalid")]
    AmendmentReasonInvalid,
    /// `version-not-found`.
    #[serde(rename = "version-not-found")]
    VersionNotFound,
    /// `amendment-cap-exhausted`.
    #[serde(rename = "amendment-cap-exhausted")]
    AmendmentCapExhausted,
    /// `administrative-edit-unchanged`.
    #[serde(rename = "administrative-edit-unchanged")]
    AdministrativeEditUnchanged,
    /// `acceptance-already-recorded`.
    #[serde(rename = "acceptance-already-recorded")]
    AcceptanceAlreadyRecorded,
    /// `acceptance-recording-party-barred`.
    #[serde(rename = "acceptance-recording-party-barred")]
    AcceptanceRecordingPartyBarred,
    /// `acceptance-required-not-recorded`.
    #[serde(rename = "acceptance-required-not-recorded")]
    AcceptanceRequiredNotRecorded,
    /// `authorization-pending`.
    #[serde(rename = "authorization-pending")]
    AuthorizationPending,
    /// `authorization-failed`.
    #[serde(rename = "authorization-failed")]
    AuthorizationFailed,
    /// `acceptance-requirement-unevaluable`.
    #[serde(rename = "acceptance-requirement-unevaluable")]
    AcceptanceRequirementUnevaluable,
    /// `verdict-authority-missing`.
    #[serde(rename = "verdict-authority-missing")]
    VerdictAuthorityMissing,
    /// `denial-reason-missing`.
    #[serde(rename = "denial-reason-missing")]
    DenialReasonMissing,
    /// `spawn-signal-already-recorded`.
    #[serde(rename = "spawn-signal-already-recorded")]
    SpawnSignalAlreadyRecorded,
    /// `acknowledgement-lines-incomplete`.
    #[serde(rename = "acknowledgement-lines-incomplete")]
    AcknowledgementLinesIncomplete,
    /// `acknowledgement-subscription-missing`.
    #[serde(rename = "acknowledgement-subscription-missing")]
    AcknowledgementSubscriptionMissing,
    /// `acknowledgement-subscription-duplicated`.
    #[serde(rename = "acknowledgement-subscription-duplicated")]
    AcknowledgementSubscriptionDuplicated,
    /// `failure-reason-missing`.
    #[serde(rename = "failure-reason-missing")]
    FailureReasonMissing,
    /// `compensation-evidence-missing`.
    #[serde(rename = "compensation-evidence-missing")]
    CompensationEvidenceMissing,
    /// `compensation-evidence-incomplete`.
    #[serde(rename = "compensation-evidence-incomplete")]
    CompensationEvidenceIncomplete,
    /// `prehold-not-in-fulfillment`.
    #[serde(rename = "prehold-not-in-fulfillment")]
    PreholdNotInFulfillment,
    /// `resume-target-missing`.
    #[serde(rename = "resume-target-missing")]
    ResumeTargetMissing,
    /// `resume-cap-exhausted`.
    #[serde(rename = "resume-cap-exhausted")]
    ResumeCapExhausted,
    /// `expiry-exempt-prehold`.
    #[serde(rename = "expiry-exempt-prehold")]
    ExpiryExemptPrehold,
    /// `expiry-not-due`.
    #[serde(rename = "expiry-not-due")]
    ExpiryNotDue,
    /// `expiry-candidate-stale`.
    #[serde(rename = "expiry-candidate-stale")]
    ExpiryCandidateStale,
    /// `cancel-reason-required`.
    #[serde(rename = "cancel-reason-required")]
    CancelReasonRequired,
    /// `direct-cancel-window-closed`.
    #[serde(rename = "direct-cancel-window-closed")]
    DirectCancelWindowClosed,
    /// `forced-failure-reason-required`.
    #[serde(rename = "forced-failure-reason-required")]
    ForcedFailureReasonRequired,
    /// `spawn-signal-not-recorded`.
    #[serde(rename = "spawn-signal-not-recorded")]
    SpawnSignalNotRecorded,
    /// `grant-source-mismatch`.
    #[serde(rename = "grant-source-mismatch")]
    GrantSourceMismatch,
    /// `grant-predecessor-unsettled`.
    #[serde(rename = "grant-predecessor-unsettled")]
    GrantPredecessorUnsettled,
    /// `grant-generation-exhausted`.
    #[serde(rename = "grant-generation-exhausted")]
    GrantGenerationExhausted,
    /// `overdue-window-not-elapsed`.
    #[serde(rename = "overdue-window-not-elapsed")]
    OverdueWindowNotElapsed,
    /// `second-approver-required`.
    #[serde(rename = "second-approver-required")]
    SecondApproverRequired,
    /// `order-not-found`.
    #[serde(rename = "order-not-found")]
    OrderNotFound,
    /// `delegation-proof-required`.
    #[serde(rename = "delegation-proof-required")]
    DelegationProofRequired,
    /// `delegation-proof-invalid`.
    #[serde(rename = "delegation-proof-invalid")]
    DelegationProofInvalid,
    /// `operation-not-permitted-for-actor`.
    #[serde(rename = "operation-not-permitted-for-actor")]
    OperationNotPermittedForActor,
    /// `page-size-exceeded`.
    #[serde(rename = "page-size-exceeded")]
    PageSizeExceeded,
    /// `filter-invalid`.
    #[serde(rename = "filter-invalid")]
    FilterInvalid,
    /// `cursor-invalid`.
    #[serde(rename = "cursor-invalid")]
    CursorInvalid,
    /// `read-store-unavailable`.
    #[serde(rename = "read-store-unavailable")]
    ReadStoreUnavailable,
}
impl Reason {
    /// All registered values.
    pub const ALL: &'static [Self] = &[
        Self::NotAdmissible,
        Self::VersionConflict,
        Self::IdempotencyMismatch,
        Self::StillProcessing,
        Self::AuthorizationContextChanged,
        Self::ExpectedVersionRequired,
        Self::RequestInvalid,
        Self::CategoryNotAdmitted,
        Self::LineNotFound,
        Self::CommercialFieldImmutable,
        Self::MixedFieldClasses,
        Self::LineCapExceeded,
        Self::DateCascadeInvalid,
        Self::AxisInvalid,
        Self::ContractNotActive,
        Self::ContractPartyIneligible,
        Self::QuantityBelowFloor,
        Self::MarketInconsistent,
        Self::ReferenceUnresolvable,
        Self::ReferenceDuplicated,
        Self::CurrencyMixed,
        Self::OverlapCardinalityExceeded,
        Self::OrderInFlightForKey,
        Self::OverlapKeyUnresolvable,
        Self::PinUnresolvable,
        Self::NoLines,
        Self::CatalogPredicatesUnavailable,
        Self::PricingRevisionUnavailable,
        Self::PricingRevisionAbsent,
        Self::CatalogPinCompositionUnavailable,
        Self::OrderBindingExpired,
        Self::OrderBindingPolicyMissing,
        Self::PurchaseCapacityExceeded,
        Self::OverlapKeyUnavailable,
        Self::CatalogPredicateFailed,
        Self::CatalogPredicateUnevaluable,
        Self::IdentityPartyUnavailable,
        Self::ContractResolutionUnavailable,
        Self::OverlapPresenceUnevaluable,
        Self::EvaluationUnavailable,
        Self::IndicativeTaxUnavailable,
        Self::MarketDivergence,
        Self::OverlapCollision,
        Self::PayerRebindingRequiresSeller,
        Self::TenantAxisImmutable,
        Self::AdministrativeFieldInAmendment,
        Self::AmendmentEmpty,
        Self::AmendmentReasonInvalid,
        Self::VersionNotFound,
        Self::AmendmentCapExhausted,
        Self::AdministrativeEditUnchanged,
        Self::AcceptanceAlreadyRecorded,
        Self::AcceptanceRecordingPartyBarred,
        Self::AcceptanceRequiredNotRecorded,
        Self::AuthorizationPending,
        Self::AuthorizationFailed,
        Self::AcceptanceRequirementUnevaluable,
        Self::VerdictAuthorityMissing,
        Self::DenialReasonMissing,
        Self::SpawnSignalAlreadyRecorded,
        Self::AcknowledgementLinesIncomplete,
        Self::AcknowledgementSubscriptionMissing,
        Self::AcknowledgementSubscriptionDuplicated,
        Self::FailureReasonMissing,
        Self::CompensationEvidenceMissing,
        Self::CompensationEvidenceIncomplete,
        Self::PreholdNotInFulfillment,
        Self::ResumeTargetMissing,
        Self::ResumeCapExhausted,
        Self::ExpiryExemptPrehold,
        Self::ExpiryNotDue,
        Self::ExpiryCandidateStale,
        Self::CancelReasonRequired,
        Self::DirectCancelWindowClosed,
        Self::ForcedFailureReasonRequired,
        Self::SpawnSignalNotRecorded,
        Self::GrantSourceMismatch,
        Self::GrantPredecessorUnsettled,
        Self::GrantGenerationExhausted,
        Self::OverdueWindowNotElapsed,
        Self::SecondApproverRequired,
        Self::OrderNotFound,
        Self::DelegationProofRequired,
        Self::DelegationProofInvalid,
        Self::OperationNotPermittedForActor,
        Self::PageSizeExceeded,
        Self::FilterInvalid,
        Self::CursorInvalid,
        Self::ReadStoreUnavailable,
    ];
}

/// Transport mapping for a registered business refusal.
#[derive(Debug, Clone, Copy)]
pub struct ReasonMapping {
    pub reason: &'static str,
    pub code: &'static str,
    pub gts_id: &'static str,
    pub category: ProblemCategory,
    pub http_status: u16,
}
impl Reason {
    /// Authoritative reason identity and wire classification.
    #[must_use]
    pub const fn mapping(self) -> ReasonMapping {
        REASON_MAPPINGS[self as usize]
    }
}
const REASON_MAPPINGS: &[ReasonMapping] = &[
    ReasonMapping {
        reason: "not-admissible",
        code: "NOT_ADMISSIBLE",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.not_admissible.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "version-conflict",
        code: "VERSION_CONFLICT",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.version_conflict.v1~"),
        category: ProblemCategory::Aborted,
        http_status: 409,
    },
    ReasonMapping {
        reason: "idempotency-mismatch",
        code: "IDEMPOTENCY_MISMATCH",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.idempotency_mismatch.v1~"),
        category: ProblemCategory::AlreadyExists,
        http_status: 409,
    },
    ReasonMapping {
        reason: "still-processing",
        code: "STILL_PROCESSING",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.still_processing.v1~"),
        category: ProblemCategory::Aborted,
        http_status: 409,
    },
    ReasonMapping {
        reason: "authorization-context-changed",
        code: "AUTHORIZATION_CONTEXT_CHANGED",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.authorization_context_changed.v1~"),
        category: ProblemCategory::Aborted,
        http_status: 409,
    },
    ReasonMapping {
        reason: "expected-version-required",
        code: "EXPECTED_VERSION_REQUIRED",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.expected_version_required.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 428,
    },
    ReasonMapping {
        reason: "request-invalid",
        code: "REQUEST_INVALID",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.request_invalid.v1~"),
        category: ProblemCategory::InvalidArgument,
        http_status: 400,
    },
    ReasonMapping {
        reason: "category-not-admitted",
        code: "CATEGORY_NOT_ADMITTED",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.category_not_admitted.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "line-not-found",
        code: "LINE_NOT_FOUND",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.line_not_found.v1~"),
        category: ProblemCategory::NotFound,
        http_status: 404,
    },
    ReasonMapping {
        reason: "commercial-field-immutable",
        code: "COMMERCIAL_FIELD_IMMUTABLE",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.commercial_field_immutable.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "mixed-field-classes",
        code: "MIXED_FIELD_CLASSES",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.mixed_field_classes.v1~"),
        category: ProblemCategory::InvalidArgument,
        http_status: 400,
    },
    ReasonMapping {
        reason: "line-cap-exceeded",
        code: "LINE_CAP_EXCEEDED",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.line_cap_exceeded.v1~"),
        category: ProblemCategory::InvalidArgument,
        http_status: 400,
    },
    ReasonMapping {
        reason: "date-cascade-invalid",
        code: "DATE_CASCADE_INVALID",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.date_cascade_invalid.v1~"),
        category: ProblemCategory::InvalidArgument,
        http_status: 400,
    },
    ReasonMapping {
        reason: "axis-invalid",
        code: "AXIS_INVALID",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.axis_invalid.v1~"),
        category: ProblemCategory::InvalidArgument,
        http_status: 400,
    },
    ReasonMapping {
        reason: "contract-not-active",
        code: "CONTRACT_NOT_ACTIVE",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.contract_not_active.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "contract-party-ineligible",
        code: "CONTRACT_PARTY_INELIGIBLE",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.contract_party_ineligible.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "quantity-below-floor",
        code: "QUANTITY_BELOW_FLOOR",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.quantity_below_floor.v1~"),
        category: ProblemCategory::InvalidArgument,
        http_status: 400,
    },
    ReasonMapping {
        reason: "market-inconsistent",
        code: "MARKET_INCONSISTENT",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.market_inconsistent.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "reference-unresolvable",
        code: "REFERENCE_UNRESOLVABLE",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.reference_unresolvable.v1~"),
        category: ProblemCategory::InvalidArgument,
        http_status: 400,
    },
    ReasonMapping {
        reason: "reference-duplicated",
        code: "REFERENCE_DUPLICATED",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.reference_duplicated.v1~"),
        category: ProblemCategory::InvalidArgument,
        http_status: 400,
    },
    ReasonMapping {
        reason: "currency-mixed",
        code: "CURRENCY_MIXED",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.currency_mixed.v1~"),
        category: ProblemCategory::InvalidArgument,
        http_status: 400,
    },
    ReasonMapping {
        reason: "overlap-cardinality-exceeded",
        code: "OVERLAP_CARDINALITY_EXCEEDED",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.overlap_cardinality_exceeded.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "order-in-flight-for-key",
        code: "ORDER_IN_FLIGHT_FOR_KEY",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.order_in_flight_for_key.v1~"),
        category: ProblemCategory::AlreadyExists,
        http_status: 409,
    },
    ReasonMapping {
        reason: "overlap-key-unresolvable",
        code: "OVERLAP_KEY_UNRESOLVABLE",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.overlap_key_unresolvable.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "pin-unresolvable",
        code: "PIN_UNRESOLVABLE",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.pin_unresolvable.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "no-lines",
        code: "NO_LINES",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.no_lines.v1~"),
        category: ProblemCategory::InvalidArgument,
        http_status: 400,
    },
    ReasonMapping {
        reason: "catalog-predicates-unavailable",
        code: "CATALOG_PREDICATES_UNAVAILABLE",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.catalog_predicates_unavailable.v1~"),
        category: ProblemCategory::ServiceUnavailable,
        http_status: 503,
    },
    ReasonMapping {
        reason: "pricing-revision-unavailable",
        code: "PRICING_REVISION_UNAVAILABLE",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.pricing_revision_unavailable.v1~"),
        category: ProblemCategory::ServiceUnavailable,
        http_status: 503,
    },
    ReasonMapping {
        reason: "pricing-revision-absent",
        code: "PRICING_REVISION_ABSENT",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.pricing_revision_absent.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "catalog-pin-composition-unavailable",
        code: "CATALOG_PIN_COMPOSITION_UNAVAILABLE",
        gts_id: gts_id!(
            "cf.bss.orders.err.v1~cf.bss.orders.catalog_pin_composition_unavailable.v1~"
        ),
        category: ProblemCategory::ServiceUnavailable,
        http_status: 503,
    },
    ReasonMapping {
        reason: "order-binding-expired",
        code: "ORDER_BINDING_EXPIRED",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.order_binding_expired.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "order-binding-policy-missing",
        code: "ORDER_BINDING_POLICY_MISSING",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.order_binding_policy_missing.v1~"),
        category: ProblemCategory::ServiceUnavailable,
        http_status: 503,
    },
    ReasonMapping {
        reason: "purchase-capacity-exceeded",
        code: "PURCHASE_CAPACITY_EXCEEDED",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.purchase_capacity_exceeded.v1~"),
        category: ProblemCategory::ResourceExhausted,
        http_status: 429,
    },
    ReasonMapping {
        reason: "overlap-key-unavailable",
        code: "OVERLAP_KEY_UNAVAILABLE",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.overlap_key_unavailable.v1~"),
        category: ProblemCategory::ServiceUnavailable,
        http_status: 503,
    },
    ReasonMapping {
        reason: "catalog-predicate-failed",
        code: "CATALOG_PREDICATE_FAILED",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.catalog_predicate_failed.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "catalog-predicate-unevaluable",
        code: "CATALOG_PREDICATE_UNEVALUABLE",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.catalog_predicate_unevaluable.v1~"),
        category: ProblemCategory::ServiceUnavailable,
        http_status: 503,
    },
    ReasonMapping {
        reason: "identity-party-unavailable",
        code: "IDENTITY_PARTY_UNAVAILABLE",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.identity_party_unavailable.v1~"),
        category: ProblemCategory::ServiceUnavailable,
        http_status: 503,
    },
    ReasonMapping {
        reason: "contract-resolution-unavailable",
        code: "CONTRACT_RESOLUTION_UNAVAILABLE",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.contract_resolution_unavailable.v1~"),
        category: ProblemCategory::ServiceUnavailable,
        http_status: 503,
    },
    ReasonMapping {
        reason: "overlap-presence-unevaluable",
        code: "OVERLAP_PRESENCE_UNEVALUABLE",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.overlap_presence_unevaluable.v1~"),
        category: ProblemCategory::ServiceUnavailable,
        http_status: 503,
    },
    ReasonMapping {
        reason: "evaluation-unavailable",
        code: "EVALUATION_UNAVAILABLE",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.evaluation_unavailable.v1~"),
        category: ProblemCategory::ServiceUnavailable,
        http_status: 503,
    },
    ReasonMapping {
        reason: "indicative-tax-unavailable",
        code: "INDICATIVE_TAX_UNAVAILABLE",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.indicative_tax_unavailable.v1~"),
        category: ProblemCategory::ServiceUnavailable,
        http_status: 503,
    },
    ReasonMapping {
        reason: "market-divergence",
        code: "MARKET_DIVERGENCE",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.market_divergence.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "overlap-collision",
        code: "OVERLAP_COLLISION",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.overlap_collision.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "payer-rebinding-requires-seller",
        code: "PAYER_REBINDING_REQUIRES_SELLER",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.payer_rebinding_requires_seller.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "tenant-axis-immutable",
        code: "TENANT_AXIS_IMMUTABLE",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.tenant_axis_immutable.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "administrative-field-in-amendment",
        code: "ADMINISTRATIVE_FIELD_IN_AMENDMENT",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.administrative_field_in_amendment.v1~"),
        category: ProblemCategory::InvalidArgument,
        http_status: 400,
    },
    ReasonMapping {
        reason: "amendment-empty",
        code: "AMENDMENT_EMPTY",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.amendment_empty.v1~"),
        category: ProblemCategory::InvalidArgument,
        http_status: 400,
    },
    ReasonMapping {
        reason: "amendment-reason-invalid",
        code: "AMENDMENT_REASON_INVALID",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.amendment_reason_invalid.v1~"),
        category: ProblemCategory::InvalidArgument,
        http_status: 400,
    },
    ReasonMapping {
        reason: "version-not-found",
        code: "VERSION_NOT_FOUND",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.version_not_found.v1~"),
        category: ProblemCategory::NotFound,
        http_status: 404,
    },
    ReasonMapping {
        reason: "amendment-cap-exhausted",
        code: "AMENDMENT_CAP_EXHAUSTED",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.amendment_cap_exhausted.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "administrative-edit-unchanged",
        code: "ADMINISTRATIVE_EDIT_UNCHANGED",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.administrative_edit_unchanged.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "acceptance-already-recorded",
        code: "ACCEPTANCE_ALREADY_RECORDED",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.acceptance_already_recorded.v1~"),
        category: ProblemCategory::AlreadyExists,
        http_status: 409,
    },
    ReasonMapping {
        reason: "acceptance-recording-party-barred",
        code: "ACCEPTANCE_RECORDING_PARTY_BARRED",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.acceptance_recording_party_barred.v1~"),
        category: ProblemCategory::PermissionDenied,
        http_status: 403,
    },
    ReasonMapping {
        reason: "acceptance-required-not-recorded",
        code: "ACCEPTANCE_REQUIRED_NOT_RECORDED",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.acceptance_required_not_recorded.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "authorization-pending",
        code: "AUTHORIZATION_PENDING",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.authorization_pending.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "authorization-failed",
        code: "AUTHORIZATION_FAILED",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.authorization_failed.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "acceptance-requirement-unevaluable",
        code: "ACCEPTANCE_REQUIREMENT_UNEVALUABLE",
        gts_id: gts_id!(
            "cf.bss.orders.err.v1~cf.bss.orders.acceptance_requirement_unevaluable.v1~"
        ),
        category: ProblemCategory::ServiceUnavailable,
        http_status: 503,
    },
    ReasonMapping {
        reason: "verdict-authority-missing",
        code: "VERDICT_AUTHORITY_MISSING",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.verdict_authority_missing.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "denial-reason-missing",
        code: "DENIAL_REASON_MISSING",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.denial_reason_missing.v1~"),
        category: ProblemCategory::InvalidArgument,
        http_status: 400,
    },
    ReasonMapping {
        reason: "spawn-signal-already-recorded",
        code: "SPAWN_SIGNAL_ALREADY_RECORDED",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.spawn_signal_already_recorded.v1~"),
        category: ProblemCategory::AlreadyExists,
        http_status: 409,
    },
    ReasonMapping {
        reason: "acknowledgement-lines-incomplete",
        code: "ACKNOWLEDGEMENT_LINES_INCOMPLETE",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.acknowledgement_lines_incomplete.v1~"),
        category: ProblemCategory::InvalidArgument,
        http_status: 400,
    },
    ReasonMapping {
        reason: "acknowledgement-subscription-missing",
        code: "ACKNOWLEDGEMENT_SUBSCRIPTION_MISSING",
        gts_id: gts_id!(
            "cf.bss.orders.err.v1~cf.bss.orders.acknowledgement_subscription_missing.v1~"
        ),
        category: ProblemCategory::InvalidArgument,
        http_status: 400,
    },
    ReasonMapping {
        reason: "acknowledgement-subscription-duplicated",
        code: "ACKNOWLEDGEMENT_SUBSCRIPTION_DUPLICATED",
        gts_id: gts_id!(
            "cf.bss.orders.err.v1~cf.bss.orders.acknowledgement_subscription_duplicated.v1~"
        ),
        category: ProblemCategory::InvalidArgument,
        http_status: 400,
    },
    ReasonMapping {
        reason: "failure-reason-missing",
        code: "FAILURE_REASON_MISSING",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.failure_reason_missing.v1~"),
        category: ProblemCategory::InvalidArgument,
        http_status: 400,
    },
    ReasonMapping {
        reason: "compensation-evidence-missing",
        code: "COMPENSATION_EVIDENCE_MISSING",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.compensation_evidence_missing.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "compensation-evidence-incomplete",
        code: "COMPENSATION_EVIDENCE_INCOMPLETE",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.compensation_evidence_incomplete.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "prehold-not-in-fulfillment",
        code: "PREHOLD_NOT_IN_FULFILLMENT",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.prehold_not_in_fulfillment.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "resume-target-missing",
        code: "RESUME_TARGET_MISSING",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.resume_target_missing.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "resume-cap-exhausted",
        code: "RESUME_CAP_EXHAUSTED",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.resume_cap_exhausted.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "expiry-exempt-prehold",
        code: "EXPIRY_EXEMPT_PREHOLD",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.expiry_exempt_prehold.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "expiry-not-due",
        code: "EXPIRY_NOT_DUE",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.expiry_not_due.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "expiry-candidate-stale",
        code: "EXPIRY_CANDIDATE_STALE",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.expiry_candidate_stale.v1~"),
        category: ProblemCategory::Aborted,
        http_status: 409,
    },
    ReasonMapping {
        reason: "cancel-reason-required",
        code: "CANCEL_REASON_REQUIRED",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.cancel_reason_required.v1~"),
        category: ProblemCategory::InvalidArgument,
        http_status: 400,
    },
    ReasonMapping {
        reason: "direct-cancel-window-closed",
        code: "DIRECT_CANCEL_WINDOW_CLOSED",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.direct_cancel_window_closed.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "forced-failure-reason-required",
        code: "FORCED_FAILURE_REASON_REQUIRED",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.forced_failure_reason_required.v1~"),
        category: ProblemCategory::InvalidArgument,
        http_status: 400,
    },
    ReasonMapping {
        reason: "spawn-signal-not-recorded",
        code: "SPAWN_SIGNAL_NOT_RECORDED",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.spawn_signal_not_recorded.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "grant-source-mismatch",
        code: "GRANT_SOURCE_MISMATCH",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.grant_source_mismatch.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "grant-predecessor-unsettled",
        code: "GRANT_PREDECESSOR_UNSETTLED",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.grant_predecessor_unsettled.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "grant-generation-exhausted",
        code: "GRANT_GENERATION_EXHAUSTED",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.grant_generation_exhausted.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "overdue-window-not-elapsed",
        code: "OVERDUE_WINDOW_NOT_ELAPSED",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.overdue_window_not_elapsed.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "second-approver-required",
        code: "SECOND_APPROVER_REQUIRED",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.second_approver_required.v1~"),
        category: ProblemCategory::FailedPrecondition,
        http_status: 400,
    },
    ReasonMapping {
        reason: "order-not-found",
        code: "ORDER_NOT_FOUND",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.order_not_found.v1~"),
        category: ProblemCategory::NotFound,
        http_status: 404,
    },
    ReasonMapping {
        reason: "delegation-proof-required",
        code: "DELEGATION_PROOF_REQUIRED",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.delegation_proof_required.v1~"),
        category: ProblemCategory::PermissionDenied,
        http_status: 403,
    },
    ReasonMapping {
        reason: "delegation-proof-invalid",
        code: "DELEGATION_PROOF_INVALID",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.delegation_proof_invalid.v1~"),
        category: ProblemCategory::PermissionDenied,
        http_status: 403,
    },
    ReasonMapping {
        reason: "operation-not-permitted-for-actor",
        code: "OPERATION_NOT_PERMITTED_FOR_ACTOR",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.operation_not_permitted_for_actor.v1~"),
        category: ProblemCategory::PermissionDenied,
        http_status: 403,
    },
    ReasonMapping {
        reason: "page-size-exceeded",
        code: "PAGE_SIZE_EXCEEDED",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.page_size_exceeded.v1~"),
        category: ProblemCategory::InvalidArgument,
        http_status: 400,
    },
    ReasonMapping {
        reason: "filter-invalid",
        code: "FILTER_INVALID",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.filter_invalid.v1~"),
        category: ProblemCategory::InvalidArgument,
        http_status: 400,
    },
    ReasonMapping {
        reason: "cursor-invalid",
        code: "CURSOR_INVALID",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.cursor_invalid.v1~"),
        category: ProblemCategory::InvalidArgument,
        http_status: 400,
    },
    ReasonMapping {
        reason: "read-store-unavailable",
        code: "READ_STORE_UNAVAILABLE",
        gts_id: gts_id!("cf.bss.orders.err.v1~cf.bss.orders.read_store_unavailable.v1~"),
        category: ProblemCategory::ServiceUnavailable,
        http_status: 503,
    },
];

/// Planned route metadata. Registration does not enable a handler.
#[derive(Debug, Clone, Copy)]
pub struct Operation {
    pub id: &'static str,
    pub method: &'static str,
    pub path: &'static str,
    pub resource: &'static str,
    pub action: &'static str,
}
/// All planned public operations; none is HTTP-enabled by the scaffold.
pub const OPERATIONS: &[Operation] = &[
    Operation {
        id: "create",
        method: "POST",
        path: "/bss-orders-lifecycle/v1/orders",
        resource: "order",
        action: "create",
    },
    Operation {
        id: "list",
        method: "GET",
        path: "/bss-orders-lifecycle/v1/orders",
        resource: "order",
        action: "read",
    },
    Operation {
        id: "get",
        method: "GET",
        path: "/bss-orders-lifecycle/v1/orders/{orderId}",
        resource: "order",
        action: "read",
    },
    Operation {
        id: "patch_order",
        method: "PATCH",
        path: "/bss-orders-lifecycle/v1/orders/{orderId}",
        resource: "order",
        action: "field_class:write|edit",
    },
    Operation {
        id: "add_line",
        method: "POST",
        path: "/bss-orders-lifecycle/v1/orders/{orderId}/lines",
        resource: "order",
        action: "write",
    },
    Operation {
        id: "patch_line",
        method: "PATCH",
        path: "/bss-orders-lifecycle/v1/orders/{orderId}/lines/{lineId}",
        resource: "order",
        action: "field_class:write|edit",
    },
    Operation {
        id: "remove_line",
        method: "DELETE",
        path: "/bss-orders-lifecycle/v1/orders/{orderId}/lines/{lineId}",
        resource: "order",
        action: "write",
    },
    Operation {
        id: "preview",
        method: "POST",
        path: "/bss-orders-lifecycle/v1/orders/preview",
        resource: "order",
        action: "preview",
    },
    Operation {
        id: "submit",
        method: "POST",
        path: "/bss-orders-lifecycle/v1/orders/{orderId}/submit",
        resource: "order",
        action: "submit",
    },
    Operation {
        id: "amend",
        method: "POST",
        path: "/bss-orders-lifecycle/v1/orders/{orderId}/amendments",
        resource: "order",
        action: "amend",
    },
    Operation {
        id: "list_versions",
        method: "GET",
        path: "/bss-orders-lifecycle/v1/orders/{orderId}/versions",
        resource: "order",
        action: "read",
    },
    Operation {
        id: "get_version",
        method: "GET",
        path: "/bss-orders-lifecycle/v1/orders/{orderId}/versions/{version}",
        resource: "order",
        action: "read",
    },
    Operation {
        id: "cancel",
        method: "POST",
        path: "/bss-orders-lifecycle/v1/orders/{orderId}/cancel",
        resource: "order",
        action: "cancel",
    },
    Operation {
        id: "hold",
        method: "POST",
        path: "/bss-orders-lifecycle/v1/orders/{orderId}/hold",
        resource: "order",
        action: "hold",
    },
    Operation {
        id: "resume",
        method: "POST",
        path: "/bss-orders-lifecycle/v1/orders/{orderId}/resume",
        resource: "order",
        action: "resume",
    },
    Operation {
        id: "force_fail",
        method: "POST",
        path: "/bss-orders-lifecycle/v1/orders/{orderId}/forced-failure",
        resource: "order",
        action: "force-fail-unreconciled",
    },
    Operation {
        id: "record_acceptance",
        method: "POST",
        path: "/bss-orders-lifecycle/v1/orders/{orderId}/acceptance",
        resource: "acceptance",
        action: "record",
    },
    Operation {
        id: "get_acceptance",
        method: "GET",
        path: "/bss-orders-lifecycle/v1/orders/{orderId}/acceptance",
        resource: "order",
        action: "read",
    },
    Operation {
        id: "list_lines",
        method: "GET",
        path: "/bss-orders-lifecycle/v1/orders/{orderId}/lines",
        resource: "order",
        action: "read",
    },
    Operation {
        id: "read_audit",
        method: "GET",
        path: "/bss-orders-lifecycle/v1/orders/{orderId}/audit",
        resource: "audit",
        action: "read",
    },
    Operation {
        id: "reflect_approval",
        method: "POST",
        path: "/bss-orders-lifecycle/v1/orders/{orderId}/approval-reflection",
        resource: "order",
        action: "approval-reflection",
    },
    Operation {
        id: "begin_fulfillment",
        method: "POST",
        path: "/bss-orders-lifecycle/v1/orders/{orderId}/begin-fulfillment",
        resource: "order",
        action: "begin-fulfillment",
    },
    Operation {
        id: "report_spawn_signal",
        method: "POST",
        path: "/bss-orders-lifecycle/v1/orders/{orderId}/spawn-signal",
        resource: "order",
        action: "spawn-signal",
    },
    Operation {
        id: "acknowledge",
        method: "POST",
        path: "/bss-orders-lifecycle/v1/orders/{orderId}/fulfillment-acknowledgement",
        resource: "order",
        action: "fulfillment-acknowledgement",
    },
    Operation {
        id: "workflow_cancel",
        method: "POST",
        path: "/bss-orders-lifecycle/v1/orders/{orderId}/workflow-cancel",
        resource: "order",
        action: "workflow-cancel",
    },
];
