//! Error types for the `PaymentApi` contract.

use serde::{Deserialize, Serialize};
use toolkit_canonical_errors_macro::resource_error;
use toolkit_contract::ContractError;

/// Resource error constructors for payment operations.
///
/// Generates typed constructors like `PaymentResourceError::not_found(detail)`.
#[resource_error(gts_id!("cf.demo.api_contracts.payment.v1~"))]
pub struct PaymentResourceError;

/// Domain errors that flow across the `PaymentApi` wire boundary as
/// typed variants (PRD #1536 contract-error envelope).
///
/// Each variant carries:
/// - `error_code` — machine-readable identifier inside `payment.v1`.
/// - canonical AIP-193 category → drives HTTP status + GTS URI.
/// - payload fields → serialized to `context["data"]` on the wire.
///
/// `From<PaymentError> for Problem` and `TryFrom<Problem> for PaymentError`
/// are auto-generated by `#[derive(ContractError)]`. Unknown
/// (`error_domain`, `error_code`) pairs from peers running a newer SDK
/// bounce back as the original `Problem` so the caller can still handle
/// the response.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ContractError)]
#[error_domain("payment.v1")]
#[non_exhaustive]
pub enum PaymentError {
    /// Account doesn't have enough balance for the requested amount.
    #[error_code("INSUFFICIENT_FUNDS")]
    #[canonical(FailedPrecondition)]
    InsufficientFunds {
        available_cents: i64,
        required_cents: i64,
    },

    /// Account is in a state that forbids new charges (closed, frozen, etc).
    #[error_code("ACCOUNT_NOT_ACTIVE")]
    #[canonical(FailedPrecondition)]
    AccountNotActive { account_id: String, reason: String },

    /// Caller exceeded per-account or per-tenant rate limits.
    #[error_code("RATE_LIMITED")]
    #[canonical(ResourceExhausted)]
    RateLimited { retry_after_sec: u32 },
}
