#!/usr/bin/env python3
"""Render review tables from the manually reviewed S1-07 ledger. --check is read-only."""
import argparse,json,os
from pathlib import Path
HERE=Path(__file__).resolve().parent
BASE=HERE.parent
ROOT=BASE.parents[4]
ledger=json.loads((HERE/'ledger.json').read_text());queue=json.loads((HERE/'queue.json').read_text())
def esc(s):return s.replace('|','\\|').replace('\n',' ')
def link(path,label):return f'[{label}]({os.path.relpath(ROOT/path,HERE)})'
lines=['# Upstream implementation and deployment ledger','', 'Generated by `render_readiness.py` from [ledger.json](ledger.json). All 44 requirement IDs retain their source identity. Existing code, local test evidence and deployment acceptance are separate columns/records. No owner conformance or deployment is claimed; missing schema/profile/provider/identity/grant values are explicitly null in the JSON.','', 'Exact current Cargo versions, manifest paths, test names and required feature flags are in [cargo-snapshot.json](cargo-snapshot.json), validated against Cargo metadata. All owner seam-conformance commands are null until actual targeted suites exist; local fixture commands in the JSON are runnable but cannot satisfy those gates.','', '| Requirement | Owner / source status | Remaining work / package | Required owner conformance |','|---|---|---|---|']
for r in ledger['requirements']:
 id=r['id'].split('-upreq-',1)[1];p=ledger['provider_profiles'][r['provider_profile']]
 lines.append(f'| `{id}` | {esc(p["owner"])}; `{r["source_capability"]}` | {esc(r["remaining_work"])} **{" / ".join(r["implementation_packages"])}** | {esc(r["conformance"]["required_scenario"])} Gate: `{r["gate"]}`. |')
lines+=['','## Provider contracts and required authority','','| Provider | Source and exact contract boundary | Required authority / scope |','|---|---|---|']
for id,p in ledger['provider_profiles'].items():
 source=', '.join(link(s,Path(s).name) for s in p['source_paths'])
 lines.append(f'| {p["owner"]} | {esc(p["contract"])} {source} | {esc(p["authority_required"])} {esc(p["supported_scope"])} |')
lines+=['','## Conditional and deferred scope','','| Scope | Disposition | Package |','|---|---|---|']
for s in ledger['scope_dispositions']:lines.append(f'| `{s["id"]}` — disabled | {esc(s["disposition"])} | {s["package"]} |')
lines+=['','## Local evidence, not owner deployment acceptance','','| Evidence | Recorded result / venue | Report |','|---|---|---|']
for id,e in ledger['evidence'].items():lines.append(f'| `{id}` | {esc(e["recorded_result"])}; {e["venue"]}. | [{e["report"]}](../{e["report"]}) |')
lines+=['','Recorded local results come from earlier S1-02–06 reports; this table does not report new Rust/provider test runs. S1-07 validates the inventory and dispatch structure. [Execution report](../READINESS.md) describes next steps and production evidence requirements.','']
rendered={'UPSTREAM.md':'\n'.join(lines)}
lines=['# Execution queue','', f'Generated from [queue.json](queue.json). Next assignment: **{queue["next_assignment"]}**. S5-01 contract reconciliation is locally verified; schema/repositories and commercial port/profile work can proceed. This document dispatches work; it does not launch workers or provision providers.','', 'Start dependencies and completion dependencies are separate. A workstream may have narrower slices that begin earlier; the original package plan remains authoritative. The graph checks both edge types for cycles. The source package census includes all 70 numbered packages; S4-08 and S5-06 each have early/later splits.','', '| Workstream | Packages / owner | Start after | Finish additionally after | Deliverable / completion gate |','|---|---|---|---|---|']
for u in queue['dispatch_units']:
 lines.append(f'| `{u["id"]}` | {" / ".join(u["packages"])} — {u["owner"]} | {", ".join(u["start_after"]) or "Local S1 baseline"} | {", ".join(u["completion_after"]) or "—"} | {esc(u["start_deliverable"])} {esc(u["completion_gate"])} |')
lines+=['','## Important early slices','']+['- '+s for s in queue['slices']]
lines+=['','## Every numbered package','','| Package | Work | Status / evidence | Source plan |','|---|---|---|---|']
for p in queue['packages']:
 evidence=f'[{p["evidence"]}](../{p["evidence"]})' if p['evidence'] else 'Implementation remains planned'
 lines.append(f'| {p["id"]} | {esc(p["title"])} | {p["status"]}; {evidence} | [{p["plan"]}](../{p["plan"]}) |')
lines+=['','Local verification is scoped to the linked report; S1 owner gaps and S2-01 disabled business readiness remain explicit. The queue is not an estimate of equal-sized tasks or a production completion percentage.','']
rendered['QUEUE.md']='\n'.join(lines)
parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
for name,body in rendered.items():
 path=HERE/name
 if args.check:
  if not path.is_file() or path.read_text()!=body:raise SystemExit('stale rendered ledger: '+name)
 else:path.write_text(body)
print('Readiness tables '+('verified' if args.check else 'rendered'))
