#!/usr/bin/env python3
"""toolkit-pr-review: the deterministic half of the review skill.

The orchestrator prompt decides whether a defect is real and how to word it. Everything
that has one correct answer lives here: resolving the PR, parsing the diff, classifying
files, snapshotting sources, estimating cost, validating coordinates, and building the
GitHub payload.

Both harnesses call this same code. They previously carried two independent
implementations of the same flow and had already drifted on five behaviours, each
divergence meaning the same PR got a different review depending on who ran it.

Usage:
    review.py prepare --pr 4777 [--repo owner/name]
    review.py prepare --local [--branch REF] [--base REF]
    review.py prepare --from-diff F --from-meta F     # offline, no network

Exit codes:
    0  ok
    1  error
    2  the run would exceed --max-total-tokens; nothing was written
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import budget            # noqa: E402
import classify          # noqa: E402
import diffparse         # noqa: E402
import ghsource          # noqa: E402

SCHEMA_VERSION = 3


def _snapshot_path(work: Path, path: str) -> Path:
    """Mirror the repo tree under files/.

    The scheme this replaces escaped `/` to `__`, which is not injective:
    `gears/mini__chat/src/lib.rs` and `gears/mini/chat/src/lib.rs` produce the same name,
    so one snapshot silently overwrote the other and a shard reviewed the wrong file's
    contents under the right file's name.
    """
    target = (work / "files" / path).resolve()
    root = (work / "files").resolve()
    if root not in target.parents and target != root:
        raise ghsource.SourceError(f"refusing to write a snapshot outside files/: {path}")
    return target


RULES_SRC = Path(__file__).resolve().parents[3] / "docs/toolkit-pr-review/rules"
RULES_OUT = Path(__file__).resolve().parents[3] / "docs/toolkit-pr-review/agent-rules"
TOOLCHAIN = Path(__file__).resolve().parents[3] / "rust-toolchain.toml"

# RUST-DEP-001 compares these two against each other, so when a PR changes one the
# other is snapshotted as read-only context. See the counterpart block in `prepare`.
ADVISORY_PAIR = ("deny.toml", ".cargo/audit.toml")

WHY = re.compile(r"^\s+why:")
# A version gate at the very end of a line gates the whole criterion. When prose follows
# the marker ("`Requires Rust >= 1.98` for the derive fast path that exposes it") the gate
# covers only part of it and the criterion stays live on an older toolchain, so it must
# not be dropped. Ten of the fourteen Enforcement markers are partial in the same way.
WHOLE_GATE = re.compile(r"`Requires Rust >= ([0-9.]+)`\s*$")


def _pin() -> tuple[int, ...]:
    m = re.search(r'channel\s*=\s*"([0-9.]+)"', TOOLCHAIN.read_text(encoding="utf-8"))
    return tuple(int(x) for x in m.group(1).split(".")) if m else (0,)


def render_rules(check_only: bool = False) -> int:
    """Write the agent-facing rule corpus: triggers without rationale, live gates only.

    `rules/*.md` is what a person reads and edits; it keeps every criterion and every
    explanation. This emits what a shard agent reads, which is the same criteria with the
    `why:` rationale removed and with criteria gated above the pinned toolchain omitted,
    because those cannot produce a finding today and only cost the agent attention.
    """
    pin = _pin()
    RULES_OUT.mkdir(parents=True, exist_ok=True)
    changed, kept, dropped = [], 0, 0

    for src in sorted(RULES_SRC.glob("*.md")):
        out_lines: list[str] = []
        skipping_why = False
        for line in src.read_text(encoding="utf-8").splitlines():
            if WHY.match(line):
                skipping_why = True
                continue
            if skipping_why:
                # rationale wraps onto further-indented lines; it ends at a blank line,
                # a bullet, or a heading
                if line.strip() and line.startswith("  ") and not line.lstrip().startswith(("-", "#")):
                    continue
                skipping_why = False
            m = re.match(r"^\s*-\s+(\S.*)$", line)
            if m:
                g = WHOLE_GATE.search(m.group(1))
                if g and tuple(int(x) for x in g.group(1).split(".")) > pin[: len(g.group(1).split("."))]:
                    dropped += 1
                    skipping_why = True
                    continue
                kept += 1
            out_lines.append(line)

        body = "\n".join(out_lines).rstrip("\n") + "\n"
        body = (f"<!-- Generated by review.py render-rules from docs/toolkit-pr-review/rules/{src.name}.\n"
                f"     Do not edit. Edit the source module; it keeps the rationale this drops. -->\n\n"
                + body)
        dst = RULES_OUT / src.name
        if not dst.exists() or dst.read_text(encoding="utf-8") != body:
            changed.append(dst.name)
            if not check_only:
                dst.write_text(body, encoding="utf-8")

    src_b = sum(f.stat().st_size for f in RULES_SRC.glob("*.md"))
    out_b = sum(len((RULES_OUT / f.name).read_text(encoding="utf-8").encode())
                for f in RULES_SRC.glob("*.md") if (RULES_OUT / f.name).exists())
    print(f"{kept} criteria kept, {dropped} dropped as gated above the pinned toolchain")
    print(f"source {src_b:,} b  ->  agent-facing {out_b:,} b")
    if check_only and changed:
        print(f"error: agent-rules/ is stale: {', '.join(changed)}. Run render-rules.",
              file=sys.stderr)
        return 1
    if changed and not check_only:
        print(f"wrote {len(changed)} file(s)")
    return 0


def cmd_render_rules(args: argparse.Namespace) -> int:
    return render_rules(check_only=args.check)


def cmd_prepare(args: argparse.Namespace) -> int:
    work = Path(args.work_dir) if args.work_dir else Path(
        tempfile.mkdtemp(prefix="toolkit-pr-review.")
    )
    (work / "files").mkdir(parents=True, exist_ok=True)
    (work / "out").mkdir(exist_ok=True)

    # --- resolve the target and get the diff -------------------------------------
    if args.from_diff:
        diff_text = Path(args.from_diff).read_text(errors="replace")
        meta = json.loads(Path(args.from_meta).read_text()) if args.from_meta else {}
        repo = meta.get("repo") or args.repo or "offline/fixture"
        mode = "pr" if meta.get("number") else "local"
        head_sha = meta.get("headRefOid", "")
        base_sha = meta.get("baseRefOid", "")
        pr_number = meta.get("number")
    elif args.pr:
        repo = ghsource.resolve_repo(args.repo)
        meta = ghsource.fetch_pr_meta(args.pr, repo)
        head_sha, base_sha = meta["headRefOid"], meta["baseRefOid"]
        pr_number, mode = args.pr, "pr"
        diff_text = ghsource.pr_diff(args.pr, repo)
    else:
        repo = ghsource.resolve_repo(args.repo)
        branch = args.branch or ghsource.run(
            ["git", "symbolic-ref", "--short", "-q", "HEAD"]).strip()
        if not branch:
            print("HEAD is detached; pass --branch", file=sys.stderr)
            return 1
        base_sha = ghsource.local_base(args.base, branch)
        head_sha = ghsource.run(["git", "rev-parse", branch]).strip()
        pr_number, mode = None, "local"
        meta = {"branch": branch, "base": base_sha}
        diff_text = ghsource.run(["git", "diff", f"{base_sha}...{branch}"])

    # Every mode writes meta.json: the harnesses read the title, the branch and the SHAs
    # from it for the summary, and a mode-dependent file means each of them needs a
    # fallback path that only runs in local mode and therefore never gets exercised.
    (work / "meta.json").write_text(json.dumps(meta, indent=2))
    (work / "diff.patch").write_text(diff_text)
    parsed = diffparse.parse(diff_text)

    # --- classify -----------------------------------------------------------------
    in_scope = [p for p in sorted(parsed) if classify.in_scope(p)]
    skipped = [p for p in sorted(parsed) if not classify.in_scope(p)]

    offline = bool(args.from_diff)
    blob_source = "fixture" if offline else "git"
    if not offline:
        shas = [s for s in (head_sha, base_sha) if s]
        if not ghsource.ensure_objects(repo, pr_number, shas):
            blob_source = "contents-api"

    files: dict[str, dict] = {}
    for path in in_scope:
        fd = parsed[path]
        ref = base_sha if fd.status == "deleted" else head_sha
        content: bytes | None = None
        if classify.snapshotable(path) and not offline and ref:
            content = ghsource.read_blob_git(ref, path)
            if content is None:
                content = ghsource.read_blob_api(repo, ref, path)
                if content is not None:
                    blob_source = "contents-api"
            if content is None:
                # Both readers failed for a file the contract says to snapshot. Carrying
                # on leaves snapshot=None, which an agent cannot tell apart from a file
                # that is deliberately never snapshotted, so it reviews the diff alone
                # and nothing says the source was missing. Offline runs and files in
                # NEVER_SNAPSHOT do not reach here.
                raise ghsource.SourceError(
                    f"no snapshot for {path} at {ref}: neither the local object database "
                    f"nor the contents API returned it"
                )
        rec: dict = {
            "status": fd.status,
            "old_path": fd.old_path,
            "toolkit_owned": False,
            "manifest": classify.is_manifest(path),
            "bytes": 0,
            "est_tokens": 0,
            "snapshot": None,
            "snapshot_ref": "base" if fd.status == "deleted" else "head",
            "ranges": {
                "right": [list(r) for r in fd.right],
                "left": [list(r) for r in fd.left],
            },
        }
        if content is not None:
            target = _snapshot_path(work, path)
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(content)
            rec["snapshot"] = f"files/{path}"
            rec["bytes"] = len(content)
            rec["toolkit_owned"] = classify.toolkit_owned(
                path, content.decode("utf-8", "replace"))
        diff_bytes = len(fd.text().encode())
        rec["est_tokens"] = budget.est_tokens(rec["bytes"] + diff_bytes)
        files[path] = rec

    # --- advisory counterpart -------------------------------------------------------
    # RUST-DEP-001 asks whether `.cargo/audit.toml` and `deny.toml` have drifted apart,
    # an advisory accepted in one but not the other. When the PR touches only one of
    # them the other is not in the diff, so the agent had nothing to compare against and
    # the criterion could not fire. Snapshot the counterpart as read-only context: no
    # `context.json` entry, so it stays out of `all_files` and `manifest_files` and has
    # no `ranges.right`, and a finding still anchors on the file the PR actually changed.
    # A counterpart that is absent from the repo leaves nothing under `files/`, which is
    # correct: there is nothing to drift from.
    if not offline and head_sha:
        for present, missing in (ADVISORY_PAIR, ADVISORY_PAIR[::-1]):
            if present in files and missing not in files:
                extra = ghsource.read_blob_git(head_sha, missing)
                if extra is None:
                    extra = ghsource.read_blob_api(repo, head_sha, missing)
                if extra is not None:
                    target = _snapshot_path(work, missing)
                    target.parent.mkdir(parents=True, exist_ok=True)
                    target.write_bytes(extra)

    # --- agents -------------------------------------------------------------------
    # One agent per rule module, each reading the whole diff. The two narrow modules get
    # their file list precomputed here so the agent is told what it owns instead of
    # re-deriving it: `toolkit.md` applies only to ToolKit-owned files and RUST-DEP-001
    # only to manifests, and an agent that guesses either one reviews the wrong set.
    toolkit_files = [p for p in in_scope if files[p]["toolkit_owned"]]
    manifest_files = [p for p in in_scope if files[p]["manifest"]]

    corpus_tokens = sum(files[p]["est_tokens"] for p in in_scope)
    diff_tokens = budget.est_tokens(len(diff_text.encode()))
    # `toolkit` reads only the ToolKit-owned subset, so charging it the whole corpus would
    # overstate a PR where one file in forty is framework code.
    narrow = {"toolkit": sum(files[p]["est_tokens"] for p in toolkit_files)}
    costs = budget.agent_costs(corpus_tokens, diff_tokens, narrow)
    if not toolkit_files:
        costs.pop("toolkit")
    cost = sum(costs.values())
    if cost > args.max_total_tokens:
        heavy = sorted(in_scope, key=lambda p: -files[p]["est_tokens"])[:5]
        print(
            f"This review needs about {cost:,} input tokens across {len(costs)} agents, over the "
            f"--max-total-tokens limit of {args.max_total_tokens:,}.\n"
            f"Every subject agent reads the whole diff, so cost scales with the PR, not the "
            f"agent count.\n"
            f"Heaviest files: {', '.join(heavy)}.\n"
            f"Narrow the review or raise the limit deliberately.",
            file=sys.stderr,
        )
        return 2

    # An agent with nothing in scope is not spawned: `toolkit` on a PR that touches no
    # framework code would otherwise read every file only to report nothing.
    agents = [
        {"name": m,
         "rules": f"docs/toolkit-pr-review/agent-rules/{m}.md",
         "instructions": "docs/toolkit-pr-review/agents/subject.md",
         "files": (toolkit_files if m == "toolkit" else in_scope),
         "manifest_files": (manifest_files if m == "security" else []),
         "est_tokens": costs[m]}
        for m in budget.MODULES if m in costs
    ]
    agents.append({
        "name": "architecture",
        "rules": "docs/toolkit-pr-review/agents/architecture.md",
        "instructions": "docs/toolkit-pr-review/agents/architecture.md",
        "files": in_scope,
        "manifest_files": [],
        "est_tokens": costs["architecture"],
    })

    ctx = {
        "schema_version": SCHEMA_VERSION,
        "mode": mode, "repo": repo, "pr_number": pr_number,
        "head_sha": head_sha, "base_sha": base_sha,
        "blob_source": blob_source,
        "work_dir": str(work),
        "files": files,
        "all_files": in_scope,
        "skipped_files": skipped,
        "toolkit_files": toolkit_files,
        "manifest_files": manifest_files,
        "agents": agents,
        "totals": {"files": len(in_scope), "skipped": len(skipped),
                   "agents": len(agents), "est_tokens": cost},
    }
    (work / "context.json").write_text(json.dumps(ctx, indent=2))

    print(f"{len(in_scope)} files in scope, {len(skipped)} skipped (not Rust or a manifest)")
    print(f"{len(agents)} agents, ~{cost:,} input tokens estimated")
    print(f"blob source: {blob_source}")
    for a in agents:
        scope = (f"{len(a['files'])} ToolKit-owned files" if a["name"] == "toolkit"
                 else f"{len(a['files'])} files")
        print(f"  {a['name']:<13} {scope}, ~{a['est_tokens']:,} tokens")
    print(f"WORK_DIR={work}")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="review.py", description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("prepare", help="resolve the target, shard it, snapshot sources")
    g = p.add_mutually_exclusive_group()
    g.add_argument("--pr", type=int, help="pull request number")
    g.add_argument("--local", action="store_true", help="review a local branch")
    p.add_argument("--repo", help="owner/name; inferred from the git remote otherwise")
    p.add_argument("--branch", help="local mode: branch under review (default: HEAD)")
    p.add_argument("--base", help="local mode: base ref (default: origin/HEAD, then main, master)")
    p.add_argument("--work-dir", help="reuse a directory instead of creating one")
    p.add_argument("--from-diff", help="offline: read the diff from this file")
    p.add_argument("--from-meta", help="offline: read gh pr view JSON from this file")
    p.add_argument("--max-total-tokens", type=int, default=budget.DEFAULT_MAX_TOTAL_TOKENS,
                   help="refuse the run above this estimate; nothing is written")
    p.set_defaults(func=cmd_prepare)

    r = sub.add_parser("render-rules", help="regenerate the agent-facing rule corpus")
    r.add_argument("--check", action="store_true",
                   help="exit 1 if agent-rules/ is out of date instead of rewriting it")
    r.set_defaults(func=cmd_render_rules)

    args = ap.parse_args(argv)
    try:
        return args.func(args)
    except ghsource.SourceError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
