#!/usr/bin/env python3
"""Independent S1-06 authoring oracle. --check is read-only; review regenerated bytes.

Python stdlib implements the normative D-99/D-143/D-100 frame/hash format.
Request/cursor bytes are a proposed restricted-JSON fixture profile, not a shipped codec.
No Rust implementation is invoked, and Rust tests never regenerate expected values.
"""
import copy
import hashlib
import json
import sys
from pathlib import Path
from uuid import UUID

ROOT = Path(__file__).resolve().parents[3]
DEST = ROOT / 'orders-lifecycle/tests/fixtures/conformance-v1.json'

def uid(n): return str(UUID(int=n))
def sha(raw): return hashlib.sha256(raw).hexdigest()
def frame(raw): return b'\0' if raw is None else b'\1' + len(raw).to_bytes(4, 'big') + raw
def tag(s): return s.encode('ascii') + b'\x1f'
def canonical(x):
    # This restricted fixture profile represents all numbers as exact strings;
    # keys below are ASCII, sorting by UTF-8 therefore equals UTF-16 ordering.
    return json.dumps(x,sort_keys=True,ensure_ascii=False,separators=(',',':')).encode()
FIELDS = [('hash_version','u16'),('audit_id','uuid'),('audit_tenant_id','uuid'),
 ('subject_tenant_id','uuid'),('resource_tenant_id','uuid'),('order_id','uuid'),
 ('requested_order_ref','uuid'),('sequence','u64'),('from_state','text'),('to_state','text'),
 ('trigger','text'),('outcome','text'),('actor','text'),('actor_class','text'),
 ('delegation_proof_ref','text'),('reason','text'),('changed_field','text'),
 ('prior_value','text'),('new_value','text'),('idempotency_key','text'),
 ('correlation_id','uuid'),('version','u64'),('created_at','i64'),('prev_hash','hash')]
def scalar(value,kind):
    if value is None:return None
    if kind=='uuid':return UUID(value).bytes
    if kind=='hash':return bytes.fromhex(value)
    if kind=='text':return value.encode()
    return int(value).to_bytes(2 if kind=='u16' else 8,'big',signed=kind=='i64')
def row_bytes(row):
    version=int(row['hash_version'])
    fields=FIELDS+([('caller_reason','text')] if version>=2 else [])
    raw=tag(f'VHP-BSS-ORDERS-AUDIT-ROW-v{version}')+b''.join(frame(scalar(row[n],k)) for n,k in fields)
    if version==3:
        observation=row['force_request_observation']
        raw+=frame(None if observation is None else b''.join(frame(scalar(observation[n],k)) for n,k in [('audit_sequence','u64'),('state','text'),('version','u64')]))
    return raw
def vector(id,kind,value,raw):return dict(id=id,kind=kind,input=value,preimage_hex=raw.hex(),sha256=sha(raw))

vectors=[]
tenant,order=uid(10),uid(100)
genesis=tag('VHP-BSS-ORDERS-AUDIT-GENESIS-v1')+frame(UUID(tenant).bytes)+frame(UUID(order).bytes)
vectors.append(vector('order-genesis','genesis',dict(audit_tenant_id=tenant,order_id=order),genesis))
base=dict(hash_version=1,audit_id=uid(1),audit_tenant_id=tenant,subject_tenant_id=uid(20),resource_tenant_id=tenant,order_id=order,requested_order_ref=None,sequence='1',from_state=None,to_state='draft',trigger='create',outcome='committed',actor=uid(30),actor_class='user',delegation_proof_ref=None,reason='create',changed_field=None,prior_value=None,new_value=None,idempotency_key='Create-Key ',correlation_id=uid(40),version='1',created_at='1791288000123456',prev_hash=sha(genesis),caller_reason=None)
for version in [1,2]:
 row=copy.deepcopy(base);row['hash_version']=version
 create=row_bytes(row);vectors.append(vector(f'v{version}-create','audit',row,create))
 row=copy.deepcopy(row);row.update(audit_id=uid(2),sequence='2',requested_order_ref=order,from_state='draft',to_state='draft',trigger='administrative-edit',reason='administrative-edit',changed_field='external_reference',prior_value='',new_value='café\n',resource_tenant_id=uid(11),prev_hash=sha(create))
 vectors.append(vector(f'v{version}-later-resource-change','audit',row,row_bytes(row)))
 # A resolved refusal keeps its observed state: to_state = from_state, never NULL (Foundation §3.7,
 # D-98). S2-06 gap review corrected the earlier to_state=NULL input of the three resolved-refusal
 # vectors; every other input, preimage and digest is unchanged.
 row=copy.deepcopy(row);row.update(audit_id=uid(3),sequence=None,prev_hash=None,outcome='refused',trigger='submit',reason='version-conflict',changed_field=None,prior_value=None,new_value=None)
 vectors.append(vector(f'v{version}-resolved-refusal','audit',row,row_bytes(row)))
 row=copy.deepcopy(row);row.update(audit_id=uid(4),audit_tenant_id=None,resource_tenant_id=None,order_id=None,version=None,from_state=None,to_state=None,reason='order-not-found',created_at='-1')
 vectors.append(vector(f'v{version}-unresolved-refusal','audit',row,row_bytes(row)))
row=copy.deepcopy(base);row.update(hash_version=2,audit_id=uid(5),sequence='2',prev_hash=vectors[1]['sha256'],from_state='draft',to_state='cancelled',trigger='cancel',reason='cancel',caller_reason='Requested cancellation — café',requested_order_ref=order)
vectors.append(vector('v2-after-v1-caller-reason','audit',row,row_bytes(row)))
for reason in [None,'']:
 row=copy.deepcopy(row);row.update(trigger='hold',reason='hold',from_state='submitted',to_state='on_hold',caller_reason=reason)
 vectors.append(vector('v2-caller-'+('null' if reason is None else 'empty'),'audit',row,row_bytes(row)))
# D-201 appends new cases; pre-existing inputs/preimages/digests stay frozen (except the S2-06 correction above).
for suffix in ['create','later-resource-change','resolved-refusal','unresolved-refusal']:
 row=copy.deepcopy(next(v['input'] for v in vectors if v['id']=='v2-'+suffix))
 row.update(hash_version=3,force_request_observation=None)
 vectors.append(vector('v3-'+suffix,'audit',row,row_bytes(row)))
row=copy.deepcopy(next(v['input'] for v in vectors if v['id']=='v2-after-v1-caller-reason'))
row.update(hash_version=3,force_request_observation=None,prev_hash=next(v['sha256'] for v in vectors if v['id']=='v2-after-v1-caller-reason'))
vectors.append(vector('v3-after-v2','audit',row,row_bytes(row)))
row=copy.deepcopy(next(v['input'] for v in vectors if v['id']=='v3-resolved-refusal'))
row.update(trigger='force-fail-unreconciled',reason='second-approver-required',from_state='in_fulfillment',to_state='in_fulfillment',version='7',force_request_observation=dict(audit_sequence='55',state='in_fulfillment',version='7'))
vectors.append(vector('v3-force-request','audit',row,row_bytes(row)))
for field,value in [('audit_sequence','56'),('state','on_hold'),('version','8')]:
 changed=copy.deepcopy(row);changed['force_request_observation'][field]=value
 if field=='state':changed.update(from_state=value,to_state=value)
 if field=='version':changed['version']=value
 vectors.append(vector('v3-force-changed-'+field,'audit',changed,row_bytes(changed)))
rollgen=tag('VHP-BSS-ORDERS-AUDIT-ROLLUP-GENESIS-v1')+frame(UUID(tenant).bytes)
vectors.append(vector('checkpoint-genesis','checkpoint_genesis',dict(audit_tenant_id=tenant),rollgen))
for count in [0,2]:
 members=[dict(order_id=order,audit_sequence='1',entry_hash=vectors[1]['sha256']),dict(order_id=uid(101),audit_sequence='7',entry_hash='ab'*32)][:count]
 x=dict(format_version=1,audit_tenant_id=tenant,checkpoint_sequence='1',captured_at='1791288000123456',member_count=str(count),prev_checkpoint_hash=sha(rollgen),members=members)
 fields=[('format_version','u16'),('audit_tenant_id','uuid'),('checkpoint_sequence','u64'),('captured_at','i64'),('member_count','u64'),('prev_checkpoint_hash','hash')]
 raw=tag('VHP-BSS-ORDERS-AUDIT-ROLLUP-v1')+b''.join(frame(scalar(x[n],k)) for n,k in fields)
 for m in members:raw+=b''.join(frame(scalar(m[n],k)) for n,k in [('order_id','uuid'),('audit_sequence','u64'),('entry_hash','hash')])
 vectors.append(vector('checkpoint-'+str(count)+'-members','checkpoint',x,raw))
# Each field is a JSON scalar/string/container; absent document members stay absent.
# Null is the fixed outer create/not-applicable sentinel, forbidden for non-create target/version.
request=dict(operation='submit',trigger='submit',order_id=order,seller_tenant_id=uid(20),resource_tenant_id=uid(10),payer_tenant_id=uid(30),expected_version='4',expected_draft_revision='0',contribution=dict(acceptance=True,lines=[dict(line_id=uid(101),quantity='1.2300',note='café')]))
for id,x in [('request-submit',request),('request-create',dict(request,operation='create',trigger='create',order_id=None,expected_version=None,expected_draft_revision=None,contribution={}))]:
 vectors.append(vector(id,'request',x,tag('VHP-BSS-ORDERS-REQUEST-FIXTURE-v1')+canonical(x)))
for endpoint,sort,position in [('orders','created_at:desc,id:desc',dict(created_at_micros='1791288000123456',id=order)),('versions','version:desc',dict(version='7')),('lines','created_at:asc,id:asc',dict(created_at_micros='-1',id=uid(101))),('acceptances','accepted_version:desc',dict(accepted_version='4')),('audit','created_at:asc,id:asc',dict(created_at_micros='1791288000123456',id=uid(40)))]:
 x=dict(format_version='1',endpoint=endpoint,parent_order_id=None if endpoint=='orders' else order,subject_tenant_id=tenant,subject_id=uid(30),filters={},sort=sort,position=position)
 vectors.append(vector('cursor-'+endpoint,'cursor',x,tag('VHP-BSS-ORDERS-CURSOR-FIXTURE-v1')+canonical(x)))
# Primitive probes deliberately do not claim to be valid business records.
for id,values in [('null-empty',[None,'']),('empty-null',['',None]),('adjacent-ab-c',['ab','c']),('adjacent-a-bc',['a','bc']),('unicode',['é','e\u0301','😀','\n'])]:
 raw=b''.join(frame(None if v is None else v.encode()) for v in values)
 vectors.append(vector(id,'framing',values,raw))
result=dict(format_version=1,provenance='Python stdlib independent authoring; audit normative, request/cursor fixture profiles only',vectors=vectors)
rendered=json.dumps(result,ensure_ascii=False,indent=2)+'\n'
if '--check' in sys.argv:
 if DEST.read_text()!=rendered:raise SystemExit('conformance vector drift; review changes before regeneration')
 print(f'Verified {len(vectors)} independent byte/preimage/SHA-256 vectors')
else:DEST.write_text(rendered)
