use construct_sdk::models::{FoundationNote, NewFoundationNote};
use uuid::Uuid;

/// A foundation note as the API returns it.
#[derive(Debug)]
#[toolkit_macros::api_dto(response)]
pub struct FoundationNoteDto {
    /// Identifier of the note, generated by the gear.
    #[schema(value_type = String)]
    pub id: Uuid,
    /// Tenant that owns the note: the tenant of the caller.
    #[schema(value_type = String)]
    pub tenant_id: Uuid,
    /// Note content.
    pub text: String,
}

impl From<FoundationNote> for FoundationNoteDto {
    fn from(note: FoundationNote) -> Self {
        Self {
            id: note.id,
            tenant_id: note.tenant_id,
            text: note.text,
        }
    }
}

/// What a caller supplies to create a note. The tenant is never part of the
/// request: it comes from the security context, so an unknown field, such as a
/// `tenant_id`, is refused.
#[derive(Debug)]
#[toolkit_macros::api_dto(request)]
#[serde(deny_unknown_fields)]
pub struct CreateFoundationNoteRequest {
    /// Note content. It must not be blank or contain the NUL character, and it
    /// is limited by the configured maximum length in bytes.
    pub text: String,
}

impl From<CreateFoundationNoteRequest> for NewFoundationNote {
    fn from(req: CreateFoundationNoteRequest) -> Self {
        Self::new(req.text)
    }
}
