//! Runtime gRPC helpers used by code generated by `#[toolkit::grpc_contract]`.
//!
//! The wire-level helpers live in [`toolkit_transport_grpc`]: `attach_bearer`,
//! `attach_secctx`, `attach_internal_token_grpc`, `attach_problem`,
//! `extract_problem`. This module is a thin shim that wraps the two-plane
//! metadata attachers so they produce [`TransportError`] (the macro's `?` chain
//! expects that error type):
//! - [`attach_bearer`] — tenant plane (`Authorization: Bearer`, from the
//!   `SecurityContext` argument);
//! - [`attach_internal_token`] — platform plane (`X-ToolKit-Internal-Token`,
//!   from the runtime credential, not the argument).
//!
//! It also provides [`map_tonic_status`], which classifies a `tonic::Status`
//! into the `TransportError` taxonomy used by the rest of the contract runtime.

use tonic::Code;
use tonic::Status;
use tonic::metadata::MetadataMap;
use toolkit_canonical_errors::Problem;

use crate::runtime::transport_error::TransportError;

// Re-export the trait + the inner helper so generated code that references
// `#support::grpc::BearerContext` continues to resolve.
pub use toolkit_transport_grpc::BearerContext;

// `SecurityContextMarker` itself lives in [`crate::grpc_repr`] (always-on)
// so generated code can emit assertions without feature-gating. Provide
// the default impl for `toolkit_security::SecurityContext` here, gated on
// `grpc-client` since that's where the dep enters the build graph.
impl crate::grpc_repr::SecurityContextMarker for toolkit_security::SecurityContext {}

// The platform-plane context is equally a compile-time plane marker that is
// kept off the wire (its credential is injected by the runtime, not carried in
// the message), so it must satisfy the same `SecurityContextMarker` bound the
// gRPC repr guard asserts for any security-context parameter
// (`cpt-cf-adr-two-plane-auth`).
impl crate::grpc_repr::SecurityContextMarker for toolkit_security::PlatformSecurityContext {}

/// Map a [`tonic::Status`] into a [`TransportError`].
///
/// - If the server attached a [`Problem`] payload via the
///   `x-toolkit-problem-bin` binary trailer, surface it as
///   [`TransportError::Problem`].
/// - `Code::Ok` is unexpected here; mapped to [`TransportError::Network`].
/// - Every other code is preserved verbatim as [`TransportError::Grpc`].
///   Retry classification reads the code via [`TransportError::is_transient`];
///   downstream mapping into canonical categories happens in
///   `toolkit-contract::runtime::canonical`.
#[must_use]
pub fn map_tonic_status(status: &Status) -> TransportError {
    match toolkit_transport_grpc::extract_problem::<Problem>(status.metadata()) {
        Ok(Some(problem)) => return TransportError::problem(problem),
        Ok(None) => {}
        Err(problem_decode_err) => {
            tracing::warn!(
                ?problem_decode_err,
                "map_tonic_status: failed to decode problem trailer; falling back to status code",
            );
        }
    }
    let code = status.code();
    if matches!(code, Code::Ok) {
        return TransportError::network("unexpected OK status surfaced as error");
    }
    TransportError::Grpc {
        code,
        message: status.message().to_owned(),
    }
}

/// Attach the bearer token from a security context onto gRPC request
/// metadata. Wraps [`toolkit_transport_grpc::attach_bearer`] so the
/// `tonic::Status` it returns is converted into a [`TransportError`] —
/// keeping the macro's `?` operator chain uniform.
///
/// # Errors
/// Returns a [`TransportError::Grpc`] when the underlying transport-grpc
/// call fails (typically: invalid bytes in the bearer token).
pub fn attach_bearer<C>(metadata: &mut MetadataMap, ctx: &C) -> Result<(), TransportError>
where
    C: BearerContext,
{
    toolkit_transport_grpc::attach_bearer(metadata, ctx).map_err(|s| TransportError::Grpc {
        code: s.code(),
        message: s.message().to_owned(),
    })
}

/// Attach the platform-plane credential from `provider` (if any) to gRPC request
/// metadata under the `x-toolkit-internal-token` key.
///
/// gRPC sibling of the REST [`crate::runtime::http::attach_internal_token`]; both
/// delegate the attach policy to
/// [`resolve_for_attach`](crate::runtime::config::InternalTokenProvider::resolve_for_attach).
///
/// # Errors
/// [`TransportError::Grpc`] if the token is not a valid ASCII metadata value.
pub fn attach_internal_token(
    metadata: &mut MetadataMap,
    provider: Option<&crate::runtime::config::InternalTokenProvider>,
    rpc: &str,
) -> Result<(), TransportError> {
    let Some(token) =
        crate::runtime::config::InternalTokenProvider::resolve_for_attach(provider, rpc)
    else {
        return Ok(());
    };
    toolkit_transport_grpc::attach_internal_token_grpc(metadata, &token).map_err(|s| {
        TransportError::Grpc {
            code: s.code(),
            message: s.message().to_owned(),
        }
    })
}

#[cfg(test)]
#[cfg_attr(coverage_nightly, coverage(off))]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;

    #[test]
    fn preserves_unavailable_code_as_transient() {
        let status = Status::unavailable("upstream down");
        let err = map_tonic_status(&status);
        match &err {
            TransportError::Grpc { code, message } => {
                assert_eq!(*code, Code::Unavailable);
                assert_eq!(message, "upstream down");
            }
            other => panic!("unexpected: {other:?}"),
        }
        assert!(err.is_transient());
    }

    #[test]
    fn preserves_deadline_exceeded_code() {
        let status = Status::deadline_exceeded("slow");
        let err = map_tonic_status(&status);
        match &err {
            TransportError::Grpc { code, .. } => assert_eq!(*code, Code::DeadlineExceeded),
            other => panic!("unexpected: {other:?}"),
        }
        assert!(err.is_transient());
    }

    #[test]
    fn preserves_not_found_code() {
        let status = Status::not_found("missing");
        let err = map_tonic_status(&status);
        match err {
            TransportError::Grpc { code, message } => {
                assert_eq!(code, Code::NotFound);
                assert_eq!(message, "missing");
            }
            other => panic!("unexpected: {other:?}"),
        }
    }

    #[test]
    fn surfaces_problem_from_binary_trailer() {
        // Build a canonical Problem the same way a server would: from a
        // CanonicalError. The wrapper translates the `tonic::Status` →
        // `TransportError::Problem` so the contract runtime sees a single
        // shape regardless of whether the wire envelope was a Problem
        // trailer or a bare gRPC status.
        let mut metadata = MetadataMap::new();
        let problem = Problem::from(
            toolkit_canonical_errors::CanonicalError::internal(
                "broke \u{1f980} \u{43a}\u{438}\u{440}\u{438}\u{43b}\u{43b}\u{438}\u{446}\u{430}",
            )
            .create(),
        );
        assert_eq!(problem.title, "Internal");
        toolkit_transport_grpc::attach_problem(&mut metadata, &problem).unwrap();
        let mut status = Status::internal("something bad");
        *status.metadata_mut() = metadata;
        match map_tonic_status(&status) {
            TransportError::Problem { problem: p, .. } => {
                assert_eq!(p.title, "Internal");
                assert_eq!(p.status, 500);
                assert!(
                    p.problem_type.contains("internal"),
                    "expected canonical internal GTS URI, got {}",
                    p.problem_type,
                );
            }
            other => panic!("unexpected: {other:?}"),
        }
    }

    /// Verifies the wrapper correctly converts the inner `tonic::Status`
    /// failure into `TransportError::Grpc`. The deeper "did the header
    /// land?" coverage lives in `toolkit-transport-grpc`'s own tests.
    #[test]
    fn attach_bearer_returns_transport_error_on_failure() {
        struct BadBearer;
        impl BearerContext for BadBearer {
            fn bearer_value(&self) -> Option<secrecy::SecretString> {
                // Newline-containing bearer values are rejected by tonic's
                // `MetadataValue::parse`. Forces the error path through
                // the transport-grpc inner helper, which the wrapper must
                // surface as `TransportError::Grpc`.
                Some(secrecy::SecretString::from("invalid\nbearer".to_owned()))
            }
        }
        let mut md = MetadataMap::new();
        let err = attach_bearer(&mut md, &BadBearer).unwrap_err();
        assert!(matches!(err, TransportError::Grpc { .. }));
    }

    #[test]
    fn attach_internal_token_writes_dedicated_key_not_authorization() {
        use crate::runtime::config::InternalTokenProvider;
        use secrecy::SecretString;
        use toolkit_security::constants::INTERNAL_TOKEN_HEADER;

        let provider = InternalTokenProvider::from_token(SecretString::from("sa.jwt.token"));
        let mut md = MetadataMap::new();
        attach_internal_token(&mut md, Some(&provider), "svc/Method").unwrap();

        assert_eq!(md.get(INTERNAL_TOKEN_HEADER).unwrap(), "sa.jwt.token");
        assert!(md.get("authorization").is_none());
    }

    #[test]
    fn attach_internal_token_none_provider_is_noop() {
        use toolkit_security::constants::INTERNAL_TOKEN_HEADER;
        let mut md = MetadataMap::new();
        attach_internal_token(&mut md, None, "svc/Method").unwrap();
        assert!(md.get(INTERNAL_TOKEN_HEADER).is_none());
    }

    #[test]
    fn attach_internal_token_not_configured_state_is_noop() {
        use crate::runtime::config::{CredentialState, InternalTokenProvider};
        use toolkit_security::constants::INTERNAL_TOKEN_HEADER;

        let provider = InternalTokenProvider::new(|| CredentialState::NotConfigured);
        let mut md = MetadataMap::new();
        attach_internal_token(&mut md, Some(&provider), "svc/Method").unwrap();
        assert!(md.get(INTERNAL_TOKEN_HEADER).is_none());
    }

    #[test]
    fn attach_internal_token_unavailable_state_warns_but_attaches_nothing() {
        use crate::runtime::config::{CredentialState, InternalTokenProvider};
        use toolkit_security::constants::INTERNAL_TOKEN_HEADER;

        let provider =
            InternalTokenProvider::new(|| CredentialState::Unavailable("token file empty".into()));
        let mut md = MetadataMap::new();
        // Permissive: unavailable attaches nothing and does not error.
        attach_internal_token(&mut md, Some(&provider), "svc/Method").unwrap();
        assert!(md.get(INTERNAL_TOKEN_HEADER).is_none());
    }

    #[test]
    fn attach_internal_token_invalid_value_maps_to_grpc_error() {
        use crate::runtime::config::{CredentialState, InternalTokenProvider};
        use secrecy::SecretString;

        // A newline-containing token is rejected by tonic's `MetadataValue`
        // parse, exercising the error-mapping branch.
        let provider = InternalTokenProvider::new(|| {
            CredentialState::Available(SecretString::from("invalid\ntoken".to_owned()))
        });
        let mut md = MetadataMap::new();
        let err = attach_internal_token(&mut md, Some(&provider), "svc/Method").unwrap_err();
        assert!(matches!(err, TransportError::Grpc { .. }));
    }
}
