#!/usr/bin/env python3
"""Generate Rust identifiers from the reviewed S1-02 inventory, never from implementation tests."""
import argparse, json, subprocess
from pathlib import Path
HERE = Path(__file__).resolve().parent
catalog = json.loads((HERE.parent/'docs/implementation/contracts/catalog.json').read_text())
def variant(s): return ''.join(x.title() for x in s.replace('-', '_').split('_'))
s = '// Generated by generate_catalog.py from the reviewed S1-02 catalog.\n'
s += 'use toolkit_canonical_errors::ProblemCategory;\nuse toolkit_gts::gts_id;\nuse serde::{Deserialize, Serialize};\n'
for name, values in [('OrderState', catalog['states']), ('Trigger', catalog['triggers']), ('EventKind', [e['name'] for e in catalog['events']]), ('Reason', [e['reason'] for e in catalog['errors']])]:
 if name == 'EventKind': s += '#[expect(clippy::enum_variant_names, reason = "Published event identifiers retain the Orders prefix")]\n'
 s += f'/// Closed `{name}` registry from the Orders design.\n#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]\npub enum {name} {{\n'
 for value in values:
  v = value if name == 'EventKind' else variant(value)
  s += f'    /// `{value}`.\n    #[serde(rename = "{value}")]\n    {v},\n'
 s += '}\n'
 s += f'impl {name} {{\n    /// All registered values.\n    pub const ALL: &\'static [Self] = &[\n'
 for value in values:s += f'        Self::{value if name == "EventKind" else variant(value)},\n'
 s += '    ];\n}\n'
s += '''
/// Transport mapping for a registered business refusal.
#[derive(Debug, Clone, Copy)]
pub struct ReasonMapping {
    pub reason: &'static str,
    pub code: &'static str,
    pub gts_id: &'static str,
    pub category: ProblemCategory,
    pub http_status: u16,
}
impl Reason {
    /// Authoritative reason identity and wire classification.
    #[must_use]
    pub const fn mapping(self) -> ReasonMapping {
        REASON_MAPPINGS[self as usize]
    }
}
const REASON_MAPPINGS: &[ReasonMapping] = &[
'''
for e in catalog['errors']:
 s += f'            ReasonMapping {{ reason: "{e["reason"]}", code: "{e["error_code"]}", gts_id: gts_id!("{e["gts_registry_key"][4:]}"), category: ProblemCategory::{e["canonical_category"]}, http_status: {e["http_status"]} }},\n'
s += '];\n'
s += '''
/// Planned route metadata. Registration does not enable a handler.
#[derive(Debug, Clone, Copy)]
pub struct Operation {
    pub id: &'static str,
    pub method: &'static str,
    pub path: &'static str,
    pub resource: &'static str,
    pub action: &'static str,
}
/// All planned public operations; none is HTTP-enabled by the scaffold.
pub const OPERATIONS: &[Operation] = &[
'''
for o in catalog['operations']:
 s += '    Operation { '+', '.join(f'{k}: "{o[v]}"' for k,v in [('id','id'),('method','method'),('path','path'),('resource','pdp_resource'),('action','pdp_action')])+' },\n'
s += '];\n'
# rustfmt through stdin keeps check mode read-only.
formatted = subprocess.run(['rustfmt', '--edition', '2024'], input=s, text=True, check=True, capture_output=True).stdout
p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');args=p.parse_args()
path=HERE/'src/catalog.rs'
if args.check:
 if path.read_text()!=formatted:raise SystemExit('Rust catalog drift; regenerate and review')
else:path.write_text(formatted)
print('Rust contract catalog verified' if args.check else 'Rust contract catalog generated')
