//! Manual REST route registration for `PaymentApi`.
//!
//! Most routes (`charge`, `get_invoice`) are generated by the
//! `#[toolkit::rest_contract]` macro — see
//! [`api_contracts_sdk::rest::register_payment_api_rest_routes`]. This file
//! keeps the **manual** `OperationBuilder` path for the one route that opts
//! out of generation via `#[server_manual]`: the SSE `list_payments` stream.
//!
//! It demonstrates that the macro-generated registration is *additive* — the
//! returned router is chained straight into hand-written `OperationBuilder`
//! calls. The manual path remains a first-class option for any route the
//! generator does not (yet) express (SSE, complex auth, custom shapes).

use std::sync::Arc;

use axum::{Extension, Router};
use toolkit::api::OpenApiRegistry;
use toolkit::api::operation_builder::OperationBuilder;

use api_contracts_sdk::contract::PaymentApi;
use api_contracts_sdk::contract_v2::PaymentApiV2;
use api_contracts_sdk::models::PaymentSummary;

use super::handlers;

const API_TAG: &str = "API Contracts \u{2014} Payments";

/// Register **all v1** `PaymentApi` REST routes — the full v1 set used by the
/// gear and the integration tests.
///
/// Composes the two v1 registration paths on one router:
/// 1. macro-generated routes (`charge`, `get_invoice`) via
///    [`api_contracts_sdk::rest::register_payment_api_rest_routes`];
/// 2. the manual SSE `list_payments` route via [`register_manual_routes`].
///
/// This is the canonical proof that generated and hand-written
/// `OperationBuilder` registration interoperate on the same router. For the
/// v2 routes see [`register_v2_routes`] — the two compose on one router.
#[allow(clippy::needless_pass_by_value)]
pub fn register_routes(
    router: Router,
    openapi: &dyn OpenApiRegistry,
    service: Arc<dyn PaymentApi>,
) -> Router {
    let router = api_contracts_sdk::rest::register_payment_api_rest_routes(
        router,
        openapi,
        Arc::clone(&service),
    );
    register_manual_routes(router, openapi, service)
}

/// Register the macro-generated **v2** routes under `/api/api-contracts/v2`.
///
/// Kept separate from [`register_routes`] so the two major versions compose on
/// one router independently (ADR-0007: parallel versions served side by side
/// during a migration window) — callers that only need v1 are unaffected.
/// v2 declares no `#[server_manual]` method, so it has no hand-written
/// counterpart and needs no `Extension` of its own.
pub fn register_v2_routes(
    router: Router,
    openapi: &dyn OpenApiRegistry,
    service_v2: Arc<dyn PaymentApiV2>,
) -> Router {
    api_contracts_sdk::rest_v2::register_payment_api_v2_rest_routes(router, openapi, service_v2)
}

/// Register the routes that are kept **manual** (not macro-generated).
///
/// Currently just the SSE `list_payments` endpoint, marked `#[server_manual]`
/// on the projection trait. `service` is layered as an axum [`Extension`] so
/// the streaming handler can resolve `Arc<dyn PaymentApi>` per request.
///
/// Composes with the generated routes: call
/// `register_payment_api_rest_routes(router, openapi, svc)` first, then pass
/// the returned router here.
#[allow(clippy::needless_pass_by_value)]
pub fn register_manual_routes(
    router: Router,
    openapi: &dyn OpenApiRegistry,
    service: Arc<dyn PaymentApi>,
) -> Router {
    // GET /api/api-contracts/v1/payments — SSE stream of PaymentSummary items.
    let router = OperationBuilder::get("/api/api-contracts/v1/payments")
        .operation_id("api_contracts.list_payments")
        .summary("List payments (SSE)")
        .description(
            "Server-sent event stream of payment summaries, optionally filtered by \
             status and currency. The stream is terminated by a synthetic \
             `event: done` frame.",
        )
        .tag(API_TAG)
        .authenticated()
        .no_license_required()
        .query_param(
            "status",
            false,
            "Filter by payment status (pending|completed|failed)",
        )
        .query_param("currency", false, "Filter by ISO 4217 currency code")
        .handler(handlers::list_payments_handler)
        .sse_json::<PaymentSummary>(openapi, "SSE stream of PaymentSummary items")
        .standard_errors(openapi)
        .register(router, openapi);

    router.layer(Extension(service))
}
