//! Public models of the Construct gear.
//!
//! Transport-agnostic data structures that define the contract between the
//! gear and its consumers. `#[domain_model]` keeps infrastructure types out of
//! them at compile time.

use toolkit_macros::domain_model;
use uuid::Uuid;

/// A stored foundation note. It exists only to give the gear shell one real
/// entity behind the secure ORM and is replaced by Construct's own model.
#[domain_model]
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub struct FoundationNote {
    /// Unique identifier of the note, generated by the gear.
    pub id: Uuid,
    /// Owning tenant, taken from the caller's security context and never from
    /// caller input.
    pub tenant_id: Uuid,
    /// Note content.
    pub text: String,
}

impl FoundationNote {
    /// Creates a note. `tenant_id` must originate from the security context.
    #[must_use]
    pub fn new(id: Uuid, tenant_id: Uuid, text: String) -> Self {
        Self {
            id,
            tenant_id,
            text,
        }
    }
}

/// Input for creating a [`FoundationNote`]. The tenant comes from the caller's
/// security context.
#[domain_model]
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub struct NewFoundationNote {
    /// Note content supplied by the caller.
    pub text: String,
}

impl NewFoundationNote {
    /// Creates the input for a new note.
    #[must_use]
    pub fn new(text: impl Into<String>) -> Self {
        Self { text: text.into() }
    }
}

#[cfg(test)]
#[path = "models_tests.rs"]
mod models_tests;
